---
title: "White House Statements Filtering"
author: "Jenna Gibson"
date: "December 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(stringr)
library(purrr)
library(lubridate)
library(data.table)
```


##Load scraped data

```{r}

load("../Data/white_house_data.RData")

dat$date <- mdy(dat$date)

head(dat)

```


##Filtering for only NK related docs

```{r}

unnested <- dat %>%
  unnest(text)


filter_text <- function(i){
  return(str_detect(i, "North Korea|Korea, North|Democratic People's Republic of Korea|DPRK|Kim"))
} 

nk_texts <- unnested %>% 
  mutate(nk = map_lgl(text, filter_text)) %>%
  filter(nk == T)

```


##Searching for all mentions of "Kim"

```{r}

#Function to remove reporter questions
Remove_Qs <- function(i){
  return(str_detect(i, "^Q()", negate = T))
}

#Removing all questions
nk_texts <- nk_texts %>%
  mutate(no_q = map_lgl(text, Remove_Qs)) %>%
  filter(no_q == T) 

#Find mentions of Kim specifically
find_kim <- function(i){
  return(str_detect(i, "Kim"))
}

#Removing all non-Kim texts
kim_texts <- nk_texts %>%
  mutate(kim = map_lgl(text, find_kim)) %>%
  filter(kim == T)

#Removing all news clips
Remove_news <- function(i){
  return(str_detect(i, "News Clips", negate = T))
}

kim_texts$statement_type[221] <- "Statements & Releases" #one observation missing - throwing an error below

kim_texts <- kim_texts %>%
  mutate(no_news = map_lgl(statement_type, Remove_news)) %>%
  filter(no_news == T) 


kim_texts$text[11]

```

##Getting word directly before Kim - presumably title

```{r}

kim_texts <- kim_texts %>%
  mutate(mention = str_extract_all(text, "[A-Za-z'-]+ Kim+ [A-Za-z'-]+ [A-Za-z'-]+|Kim+ [A-Za-z'-]+ [A-Za-z'-]+|[A-Za-z'-]+ Kim.|[A-Za-z'-]+. Kim+ [A-Za-z'-]+|. Kim [A-Za-z'-]+")) %>%
  na.omit()

#fixing 3 observations
kim_texts$mention[216] <- "the Kim regime."
kim_texts$mention[230] <- "the Kim regime." 
kim_texts$mention[232] <- "the Kim regime." 


kim_texts_all <- kim_texts %>% #unnest multiple mentions from one paragraph
  unnest(mention)

table(kim_texts_all$mention) #view all mentions

```

##Remove other Kims - ie Kim Jung-sook, Kim Dong Chul

```{r}

Remove_Kims <- function(i){
  return(str_detect(i, "Jung-sook|Dong-chul|Dong Chul|Lady|Sung|Honorable|Kwang-jin|Jong-il|Mrs.|Tony|Yong|Kimb|Hak Song", negate = T)) #detecting other Kims besides KJU
}

wh_kim_texts <- kim_texts_all %>%
  mutate(kju = map_lgl(mention, Remove_Kims)) %>% #mapping to leave only kju mentions
  filter(kju == T) %>%
  select(ID, statement_type, date, title, text, mention) #cleaning up and removing unncessary columns

table(wh_kim_texts$mention)

save(wh_kim_texts, file ="../Data/wh_kim_texts.RData")

```


